// generated with:
// .split('\n').map(l => l.replaceAll('\t', ' ').split(' ').reverse()).map(([value, country, ...donor]) => [donor.reverse().join(' '), country, value])

import type { Countries } from "../../../src/utils/locales";

export const fromPdfDonations: Record<
  string,
  {
    parties: Record<string, [string, Countries, string][]>;
    foundations: Record<string, [string, Countries, string][]>;
  }
> = {
  2018: {
    parties: {
      ALDE: [
        ["Minor donors", "??", "12.682,00"],
        ["American Chamber of Commerce to the EU", "BE", "6.000,00"],
        ["Bayer AG", "DE", "18.000,00"],
        ["Deloitte to Deloitte Services & Investments NV", "BE", "13.000,00"],
        ["Eli Lilly Benelux SA", "BE", "1.200,00"],
        [
          "European Telecommunications Network Operators Association",
          "BE",
          "1.200,00",
        ],
        ["Fleishman-Hillard SA", "BE", "1.200,00"],
        ["Fooddrinkeurope AISBL", "BE", "18.000,00"],
        ["Fti Consulting Belgium SA", "BE", "5.000,00"],
        ["Google Belgium NV", "BE", "15.000,00"],
        ["GSM Association", "UK", "18.000,00"],
        ["Microsoft SA/NV", "BE", "18.000,00"],
        ["Pangea Public Affairs", "BE", "1.200,00"],
        ["Philip Morris Benelux BVBA", "BE", "2.400,00"],
        ["Sky UK Limited", "UK", "12.000,00"],
        ["Stuart Delivery SL", "ES", "7.000,00"],
        ["Syngenta Crop Protection NV", "BE", "18.000,00"],
        ["The Walt Disney Company Benelux BVBA", "BE", "18.000,00"],
        ["Uber BV", "NL", "15.000,00"],
        ["Yelp Ireland LTD", "IE", "18.000,00"],
      ],
      ECPM: [
        ["Minor donors", "??", "15.606,00"],
        [
          "Asociatia Evanghelistica Si De Caritate Isus Speranta Romaniei",
          "RO",
          "2.500,00",
        ],
        ["D.G.T. Limited", "MT", "6.000,00"],
        ["Estiom", "NL", "500,00"],
        ["European Coalition for Israel", "BE", "714,50"],
        ["European Dignity Watch", "BE", "10.000,00"],
        ["Forum Plus Hrvatska", "HR", "3.000,00"],
        [
          "Foundation for International Christian-Democratic Development",
          "NL",
          "8.535,00",
        ],
        ["Fundatia Beraca-Sighisoara", "RO", "1.800,00"],
        ["Henk's Finance & Advice", "NL", "600,00"],
        ["M.T.I. SPRL", "BE", "500,00"],
        ["Meine Stimme - Verein", "AT", "10.000,00"],
        ["Stichting ForumC", "NL", "500,00"],
        ["Stichting voor CHRISTELIJK FILOSOFIE", "NL", "500,00"],
        ["Stichting Vormingsactiviteiten Oost-Europa", "NL", "13.210,49"],
      ],
      ECR: [
        ["", "PT", "6.000,00"],
        ["All Faiths Network", "UK", "2.000,00"],
        ["Arbitre Communications Limited", "UK", "18.000,00"],
        [
          "AT&T Global Network Services Belgium Luxembourg SPRL",
          "BE",
          "12.989,82",
        ],
        ["", "AT", "18.000,00"],
        [
          "Fundacion para la Mejora de la Vida, la Cultura y la Sociedad",
          "ES",
          "2.000,00",
        ],
        ["", "AT", "18.000,00"],
        ["Interaktywne Muzeum Państwa Krzyżackiego", "PL", "11.922,57"],
        ["", "AT", "18.000,00"],
        ["Stowarzyszenie Twórców Dla Rzeczypospolitej", "PL", "4.820,48"],
        [
          "Triple A Analytics Institut für wirtschaftswissenschaftliche Studien GmbH",
          "AT",
          "18.000,00",
        ],
        ["", "AT", "18.000,00"],
        ["Utopia Lab s.r.l.", "IT", "2.000,00"],
      ],
      EFA: [
        ["Minor donors", "??", "6.490,00"],
        ["Inseme Per a Corsica", "FR", "500,00"],
        ["Régions et Peuples Solidaires", "FR", "9.915,00"],
        ["STG Ter Bevordering vd. Nederlandse Kenniseconomie", "NL", "825,00"],
      ],
      EGP: [["Minor donors", "??", "1.050,43"]],
      EL: [["Minor donors", "??", "98,80"]],
    },
    foundations: {
      IDF: [["Rassemblement National ", "FR", "12.000,00"]],
      CF: [
        ["European Centre For Minority lssues (ECMI)", "DE", "9.460,39"],
        ["Fundacion Moncho Reboiras", "ES", "1.232,55"],
        ["lstituto d¡ Stud¡ e Ricerche Camillo Bellieni", "IT", "1.715,65"],
        ["Network to Promote Linguistic Diversity (NPLD)", "BE", "12.777,38"],
      ],
      ELF: [
        ["Minor donors", "??", "5.420,00"],
        [
          "AT&T Global Networks Services Belgium Luxembourg SPRL",
          "BE",
          "13.130,25",
        ],
        ["Ciudadanos", "ES", "2.000,00"],
      ],
      FEPS: [
        ["Minor donors", "??", "401,50"],

        ["Associazione Economia Civile", "IT", "8.763,42"],
        [
          "AT&T Global Network Services Belgium Luxembourg SPRL",
          "BE",
          "13.132,46",
        ],
        ["Burson-Marsteller SPRL", "BE", "18.000,00"],
        ["Coca-Cola Services NV/SA", "BE", "15.000,00"],
        ["Democracy without Borders e.V.", "DE", "1.000,00"],
        ["IPPR Trading LTD", "UK", "256,81"],
        ["Microsoft NV/SA", "BE", "18.000,00"],
      ],
      GEF: [["Minor donors", "??", "6.212,00"]],
      ND: [
        ["Minor donors", "??", "9.676,50"],

        ["", "PL", "3.500,00"],
        ["Amundsen Travel OU", "EE", "12.000,00"],
        [
          "AT&T Global Networks Services Belgium Luxembourg SPRL",
          "BE",
          "12.967,33",
        ],
        [
          "British American Tobacco Western Europe Commercial Trading Limited",
          "UK",
          "18.000,00",
        ],
        ["", "ES", "8.000,00"],
        [
          "ECCP - Europejskie Centrum Projektow Pozarzadowych",
          "PL",
          "3.750,00",
        ],
        ["", "ES", "18.000,00"],
        ["Fundacion FAES", "ES", "7.500,00"],
        [
          "Foundation for Social and Economic Thinking (FSET)",
          "UK",
          "17.486,40",
        ],
        ["Fratelli d'Italia Party", "IT", "17.500,00"],
        ["Galerie Gema s.r.o.", "CZ", "16.000,00"],
        ["", "UK", "11.129,34"],
        ["Horatius Events LImited", "UK", "7.750,00"],
        ["Institute for Policy and Research", "UK", "11.045,28"],
        ["Institute of economic affairs", "UK", "500,00"],
        ["Jagello 2000", "CZ", "11.000,00"],
        ["", "ES", "6.000,00"],
        ["", "PL", "12.000,00"],
        ["", "PL", "9.000,00"],
        ["", "UK", "3.336,93"],
        ["Qed Systems a.s.", "CZ", "16.000,00"],
        ["Sir Hugh and Lady Sykes Charitable Trust", "UK", "8.541,79"],
        ["Ulster Unionist Party", "UK", "1.935,00"],
        ["Wastech a.s.", "CZ", "16.000,00"],
        ["Winglet LTD", "LV", "5.500,00"],
        ["Without Limits S.r.l.", "IT", "2.900,00"],
      ],
      SALLUX: [
        ["Minor donors", "??", "723,61"],

        ["AWS HOLDING BV", "NL", "5.000,00"],
        ["Bündnis C –Christen für Deutschland", "DE", "400,00"],
        ["ChristenUnie", "NL", "10.000,00"],
        ["European Christian Political Youth", "NL", "87,50"],
        [
          "FAFCE - Fédération des Associations Familiales Catholiques en Europe",
          "FR",
          "5.000,00",
        ],
        ["ISTITUTO ACTON", "IT", "2.000,00"],
        ["Staatkundig Gereformeerde Partij (SGP)", "NL", "10.000,00"],
        ["Taxi Boute", "NL", "60,00"],
        ["WEA Business Coalition E.V.", "DE", "10.000,00"],
      ],
      TE: [
        ["Minor donors", "??", "19.412,27"],
        ["Altersummit", "BE", "450,00"],
        ["Another Europe", "UK", "691,65"],
        ["Asia Europe Peoples Forum", "BE", "1.603,27"],
        ["Berliner Institut für kritische Theorie", "DE", "8.913,17"],
        ["Hochschülerschaft der Uni Wien", "AT", "1.600,00"],
        ["The world transformed", "UK", "225,00"],
        ["Zukunftsfond der Rep.Österreich", "AT", "2.000,00"],
      ],
      WMCES: [
        ["Adam Mickiewicz University", "PL", "438,40"],
        [
          "American Chamber of Commerce to the European Union",
          "BE",
          "6.000,00",
        ],
        [
          "Asociatia Institutul pentru Democratie Participativa (Qvorum)",
          "RO",
          "3.603,37",
        ],
        [
          "AT&T Global Networks Services Belgium Luxembourg SPRL",
          "BE",
          "13.000,00",
        ],
        [
          "Beyond the Horizon International Strategic Studies Group",
          "BE",
          "5.105,38",
        ],
        [
          "Fundacja im. Kazimierza Pulaskiego / Casimir Pulaski Foundation",
          "PL",
          "18.000,00",
        ],
        ["European Council on Foreign Affairs (ECFR)", "UK", "9.677,65"],
        ["Fokus 2031", "SI", "4.925,00"],
        ["FTI Consulting", "BE", "6.000,00"],
        [
          "Institute for Development and Social Market in Belarus and Eastern Europe",
          "LT",
          "1.770,92",
        ],
        ["Konstantinos Mitsotakis Foundation", "GR" /* was EL */, "10.018,77"],
        ["Microsoft NV/SA", "BE", "18.000,00"],
        ["Re-Imagine Europa", "BE", "1.464,39"],
        ["Slovak Security Policy Institute", "SK", "2.720,95"],
        ["The Walt Disney CompanyBenelux BVBA", "BE", "18.000,00"],
        ["Uber BV", "NL", "6.000,00"],
        ["UPS Europe SPRL", "BE", "12.000,00"],
      ],
    },
  },
  2019: {
    parties: {
      ALDE: [
        ["Minor donors", "??", "18.626,50"],
        [
          "American Chamber of Commerce to the European Union ",
          "BE",
          "6.000,00",
        ],
        ["Deloitte Services & Investments NV", "BE", "2.400,00"],
        ["Friedrich - Naumann - Stiftung für die Freiheit", "DE", "10.000,00"],
        ["GSM Association", "UK", "3.000,00"],
        ["Microsoft NV/SA", "BE", "4.800,00"],
        ["TransferGo Ltd", "UK", "11,59"],
        [
          "Alliance Party of Northern Ireland (Páirtí Comhghuaillíochta Thuaisceart Éireann)",
          "UK",
          "2.000,00",
        ],
        ["GLAS - Građansko - liberalni savez", "HR", "2.000,00"],
        ["Hrvatska socijalno liberalna stranka", "HR", "2.000,00"],
        ["Liberal Party of Gibraltar", "UK", "2.000,00"],
        ["Pametno", "HR", "2.000,00"],
        ["Stranka Alenke Bratušek (SAB)", "SI", "2.000,00"],
        ["Team Köllensperger", "IT", "1.500,00"],
      ],
      ECPM: [
        ["Minor donors", "??", "9.606,00"],
        ["Asociația PRODOCENS Media", "RO", "9.000,00"],
        ["Associação Instituto Do Pensamento Lusitano", "PT", "656,00"],
        ["ChristenUnie Reimerswaal", "NL", "394,70"],
        ["D.G.T. Limited", "MT", "4.000,00"],
        ["Estiom", "NL", "500,00"],
        ["European Freedom Network e.V.", "DE", "10.000,00"],
        ["Forum Plus Hrvatska", "HR", "2.000,00"],
        [
          "Foundation for International Christian Democratic Development (FICDD)",
          "NL",
          "12.226,00",
        ],
        ["Fundația Beraca Sighișoara", "RO", "7.000,00"],
        ["Henk's Finance & Advice", "NL", "600,00"],
        ["Israel Allies Foundation e.V.", "DE", "5.000,00"],
        ["Stichting Driestar Educatief", "NL", "1.500,00"],
        ["Stichting ForumC", "NL", "500,00"],
        ["Stichting Pillar of Fire", "NL", "5.552,50"],
        ["Stichting voor Christelijke Filosofie", "NL", "500,00"],
        [
          "Stichting Vormingsactiviteiten Oost - Europa van de SGP",
          "NL",
          "7.000,00",
        ],
      ],
      ECR: [
        ["Minor donors", "??", "2.640,00"],
        [
          "AT&T Global Network Services Belgium Luxembourg SPRL",
          "BE",
          "13.632,65",
        ],
        ["", "UK", "11.900,00"],
        ["Fundación para la Mejora de la Vida", "ES", "17.000,00"],
        ["", "LV", "4.000,00"],
        ["", "EE", "17.500,00"],
        [
          "International Association of Oil and Gas Producers",
          "UK",
          "5.000,00",
        ],
        ["Kusfors BVBA", "BE", "5.000,00"],
        ["Milano Business Consulting S.r.l.s", "IT", "17.500,00"],
        ["Mo Ka BVBA", "BE", "13.000,00"],
        ["", "UK", "6.000,00"],
        ["", "BE", "10.900,00"],
        ["Visa Engeneering S.r.l", "IT", "3.000,00"],
        ["Voter Consultancy Ltd", "UK", "18.000,00"],
        ["", "DE", "5.500,00"],
      ],
      EFA: [
        ["Minor donors", "??", "10,00"],
        ["Euskal Herria Bildu (EH Bildu)", "ES", "300,00"],
      ],
      EGP: [["Minor donors", "??", "8.726,20"]],
      ID: [["Minor donors", "??", "250,00"]],
      EL: [["Minor donors", "??", "24,22"]],
    },
    foundations: {
      CF: [
        [
          "Centre Internacional Escarré per les Minories Ètniques i les Nacions (CIEMEN)",
          "ES",
          "300,00",
        ],
        ["Istituto di Studi e Ricerche Camillo Bellieni", "IT", "300,00"],
        ["Kurdish Institute Brussels vzw", "BE", "300,00"],
        ["Slobodna Država Rijeka / Stato Libero di Fiume", "HR", "1.827,45"],
      ],
      ELF: [
        [
          "AT&T Global Networks Services Belgium Luxembourg SPRL",
          "BE",
          "12.041,48",
        ],
        ["Danish Liberal Democracy Programme", "DK", "250,00"],
        ["Fondazione Luigi Einaudi Onlus", "IT", "250,00"],
        ["For Freedom, for Liberal Thinking Foundation (SZA)", "HU", "250,00"],
        ["Liberas vzw", "BE", "250,00"],
      ],
      FEPS: [
        ["Fundacja Amicus Europae", "PL", "5.276,93"],
        [
          "Stichting Environment & Development Resource Centre (EDRC)",
          "BE",
          "7.993,50",
        ],
        ["Thinkyoung (IVZW)", "BE", "2.976,38"],
      ],
      GEF: [
        ["Minor donors", "??", "5.485,00"],

        ["Ceratonia Foundation", "MT", "862,50"],
        [
          "Cooperation and Development Network Eastern Europe (CDNEE)",
          "BE",
          "1.500,00",
        ],
        ["Forum za održivi razvoj Zeleni prozor", "HR", "727,20"],
        ["FYEG - Federation of Young European Greens", "BE", "1.675,00"],
        ["Green House Think Tank", "UK", "1.400,00"],
        ["Het Groene Boek vzw", "BE", "800,00"],
        ["Institut Aktivního Občanství", "CZ", "1.594,00"],
        [
          "Quercus - Associação Nacional de Conservação da Natureza",
          "PT",
          "800,00",
        ],
        ["Fundacja Strefa Zieleni", "PL", "1.650,00"],
        ["Institut za političku ekologiju", "HR", "1.120,00"],
      ],
      ND: [
        ["Minor donors", "??", "2.000,00"],

        ["", "ES", "18.000,00"],
        ["", "ES", "6.000,00"],
        [
          "AT&T Global Network Services Belgium Luxembourg SPRL",
          "BE",
          "13.599,00",
        ],
        ["Better Financial Planning Ltd", "UK", "12.000,00"],
        [
          "British American Tobacco Western Europe Commercial Trading Limited",
          "UK",
          "18.000,00",
        ],
        ["CI Consult&Research s.r.o.", "CZ", "10.000,00"],
        ["CZ Export Praha s.r.o.", "CZ", "3.853,50"],
        ["Fondazione Farefuturo", "IT", "1.008,00"],
        ["Fratelli d’Italia - Alleanza nazionale", "IT", "18.000,00"],
        ["Galerie Gema s.r.o.", "CZ", "16.000,00"],
        ["Jagello 2000, z.s.", "CZ", "10.000,00"],
        ["", "ES", "12.000,00"],
        ["QED Group a.s.", "CZ", "16.000,00"],
        ["Qed Systems a.s.", "CZ", "16.000,00"],
        ["Servicios Integrados Lasker SL.", "ES", "4.250,00"],
        ["The Institute of Economic Affairs Limited", "UK", "750,00"],
      ],
      SALLUX: [
        ["Minor donors", "??", "714,00"],
        ["Hrast - Pokret za uspješnu Hrvatsku", "HR", "2.000,00"],
        ["Nationwide Building Society", "UK", "500,00"],
        ["Stichting ForumC", "NL", "500,00"],
        ["Stichting Jubilee Campaign Nederland", "NL", "10.948,41"],
        ["Stichting voor Christelijke Filosofie", "NL", "500,00"],
        ["WEA Business Coalition e.V.", "DE", "2.500,00"],
      ],
      TE: [
        ["Minor donors", "??", "130,00"],
        ["Iratzar Fundazioa", "ES", "4.420,00"],
      ],
      WMCES: [
        ["Ajatushautomo Kompassi ry", "FI", "2.281,04"],
        [
          "American Chamber of Commerce to the European Union",
          "BE",
          "7.000,00",
        ],
        ["Antall József Tudásközpont", "HU", "14.763,94"],
        [
          "AT&T Global Networks Services Belgium Luxembourg SPRL",
          "BE",
          "16.360,00",
        ],
        ["Asociatia Societatea Liberala", "RO", "7.050,00"],
        ["Collins Institute", "IE", "200,00"],
        ["Demokratinės Politikos Institutas VŠĮ", "LT", "17.830,55"],
        ["Evropská Akademie Pro Demokracii", "CZ", "1.836,68"],
        ["Evropské hodnoty z.s.", "CZ", "17.956,95"],
        [
          "Fundación para el Análisis y los Estudios Sociales (FAES)",
          "ES",
          "18.000,00",
        ],
        ["Fundacja im. Kazimierza Pulaskiego", "PL", "18.000,00"],
        ["Microsoft NV/SA", "BE", "18.000,00"],
      ],
    },
  },
  2020: {
    parties: {
      ALDE: [
        ["Minor donors", "??", "6,524.85"],
        [
          "Alliance Party of Northern Ireland (Páirtí Comhghuaillíochta Thuaisceart Éireann) ",
          "UK",
          "2,000.00",
        ],
        ["Freedom Party (LP) ", "LT", "2,000.00"],
        ["GLAS -  Građansko - liberalni savez ", "HR", "2,000.00"],
        ["Hungarian Liberal Party (MLP) ", "HU", "2,000.00"],
        ["Team Köllensperger (TK) ", "IT", "2,000.00"],
        ["Liberal Initiative (IL) ", "PT", "2,000.00"],
        ["Liberal Party of Gibraltar (Libs) ", "UK", "2,000.00"],
        ["Stranka Alenke Bratušek (SAB) ", "SI", "2,000.00"],
        ["Pametno ", "HR", "2,000.00"],
        ["Microsoft NV/SA ", "BE", "3,000.00"],
        ["Nove SA ", "BE", "3,000.00"],
        ["Liberty Global services B.V ", "NL", "3,000.00"],
        ["Janssen Pharmaceutica ", "NL", "10,000.00"],
      ],
      ECPM: [
        ["Minor donors", "??", "7,034.74"],
        ["ASOCIATIA POLYLOGOS ", "RO", "4,000.00"],
        ["EUROPEAN FREEDOM NETWORK E.V. ", "DE", "2,000.00"],
        [
          "Foundation for International Christian Democratic Development) (FICDD) ",
          "NL",
          "7,230.00",
        ],
        ["", "DE", "5,220.00"],
        ["Henk's Finance en Advice donation ", "NL", "1,000.00"],
        ["Pro Life Campaign ", "IE", "3,000.00"],
        ["Stichting ForumC ", "NL", "250.00"],
        ["Stichting voor Christelijke Filosofie ", "NL", "500.00"],
        [
          "Stichting Vormingsactiviteiten Oost - Europa van de SGP ",
          "NL",
          "17,000.00",
        ],
      ],
      ECR: [
        ["Minor donors", "??", "4,500.00"],
        ["", "PL", "5,000.00"],
        ["", "DE", "4,000.00"],
        ["Aquind Ltd ", "UK", "18,000.00"],
        ["Asociation Cultural Foro Europa Ciudana ", "ES", "12,000.00"],
        [
          "AT&T Global Network Services Belgium Luxembourg SPRL ",
          "BE",
          "13,424.02",
        ],
        ["", "LV", "3,000.00"],
        ["", "UK", "12,000.00"],
        [
          "Centrum pro studium demokracie a kultury, o.p.s. (CDK) ",
          "CZ",
          "9,000.00",
        ],
        ["CI Consultresearch S.R.O ", "CZ", "18,000.00"],
        ["", "BE", "12,000.00"],
        ["Evropský informační projekt, z. ú. ", "CZ", "9,000.00"],
        ["Galerie A Nakladatelstvi STARA POST ", "CZ", "6,000.00"],
        ["Gamberina B Cooperativa Sociale Multiservizi ", "IT", "6,500.00"],
        ["", "EE", "12,000.00"],
        ["JAGELLO 2000, z.s. ", "CZ", "6,000.00"],
        ["Milano Business Consulting S.r.l.s ", "IT", "17,500.00"],
        ["Morea Motorvip S.L. ", "ES", "6,000.00"],
        ["Norfolk SIA ", "LV", "18,000.00"],
        ["Regma Holding SIA ", "LV", "3,000.00"],
        ["", "BE", "10,000.00"],
        ["", "BE", "12,000.00"],
        ["", "UK", "18,000.00"],
      ],
      EGP: [
        ["Minor donors", "??", "3,279.00"],
        ["ORaH", "HR", "450.00"],
      ],
      ID: [["Minor donors", "??", "4,600.00"]],
      EL: [["Minor donors", "??", "66.60"]],
    },
    foundations: {
      CF: [
        [
          "Centre Internacional Escarré per les Minories Ètniques i les Nacions (CIEMEN)",
          "ES",
          "300,00",
        ],
        ["Istituto di Studi e Ricerche Camillo Bellieni", "IT", "300,00"],
        ["Slobodna Država Rijeka / Stato Libero di Fiume", "HR", "1.876,57"],
        ["Network for the Promotion of Linguistic Diversity", "BE", "665,98"],
      ],
      ELF: [
        [
          "AT&T Global Networks Services Belgium Luxembourg SPRL",
          "BE",
          "13.218,19",
        ],
        ["Centro Luigi Einaudi", "IT", "250,00"],
        ["For Freedom, for Liberal Thinking Foundation (SZA)", "HU", "250,00"],
        ["LGBTI Liberals of Europe", "FR", "250,00"],
        ["Liberas vzw", "BE", "250,00"],
        ["Paddy Ashdown Forum", "UK", "250,00"],
      ],
      FEPS: [
        ["Democracy Without Borders", "DE", "954,15"],
        ["UNI Europa", "BE", "1.800,00"],
      ],
      GEF: [
        ["Minor donors", "??", "2.846,00"],

        [
          "Cooperation and Development Network Eastern Europe (CDNEE)",
          "BE",
          "1.738,10",
        ],
        ["Forum za održivi razvoj Zeleni prozor", "HR", "1.500,00"],
        ["Fundacja Strefa Zieleni", "PL", "3.036,50"],
        ["FYEG - Federation of Young European Greens", "BE", "2.589,50"],
        ["Green House Think Tank", "UK", "2.429,00"],
        ["Het Groene Boek vzw", "BE", "950,00"],
        ["Institut Aktivního Občanství", "CZ", "2.902,00"],
        ["Institut za političku ekologiju", "HR", "3.605,56"],
        [
          "Quercus - Associação Nacional de Conservação da Natureza",
          "PT",
          "300,00",
        ],
        ["Фондация блулинк/Bluelink", "BG", "245,00"],
        ["Πράσινο Ινστιτούτο/Green Institute", "GR", "80,00"],
      ],
      ND: [
        ["Minor donors", "??", "2.000,00"],

        ["Amundsen Travel OÜ", "EE", "12.000,00"],
        ["Asociacion Cultural Foro Europa Ciudadana", "ES", "18.000,00"],
        [
          "AT&T Global Network Services Belgium Luxembourg SPRL",
          "BE",
          "13.424,00",
        ],
        ["", "UK", "12.000,00"],
        ["CI Consult&Research s.r.o.", "CZ", "18.000,00"],
        ["Civismo y Economia Navarro", "ES", "6.000,00"],
        ["", "ES", "6.000,00"],
        ["Evropský informační projekt, z. ú.", "CZ", "8.000,00"],
        ["Fratelli d’Italia - Alleanza nazionale", "IT", "17.000,00"],
        ["Galerie a nakladatelství Stará pošta, z. ú.", "CZ", "8.000,00"],
        ["Galerie Gema s.r.o.", "CZ", "12.000,00"],
        ["Jagello 2000, z.s.", "CZ", "6.000,00"],
        ["", "PL", "9.000,00"],
        ["", "PL", "6.000,00"],
        ["", "ES", "6.000,00"],
        ["", "ES", "6.000,00"],
        ["Qed Systems a.s.", "CZ", "12.000,00"],
        ["", "ES", "18.000,00"],
        ["", "ES", "12.000,00"],
        ["", "PL", "6.000,00"],
        ["STUDIO ARX s.r.o", "CZ", "8.000,00"],
        ["Tabora Abogados SL", "ES", "6.000,00"],
        ["Uriel Inversiones, SA", "ES", "6.000,00"],
        ["Utopia Lab Bruxelles SRL", "BE", "3.000,00"],
        ["", "PL", "7.000,00"],
        ["", "PL", "8.000,00"],
      ],
      SALLUX: [
        ["Minor donors", "??", "1.975,00"],
        ["Hrast - Pokret za uspješnu Hrvatsku", "HR", "3.000,00"],
        ["Achmea Interne Diensten N.V.", "NL", "5.000,00"],
        ["Stichting ForumC", "NL", "250,00"],
        ["Stichting Jubilee Campaign Nederland", "NL", "5.000,00"],
        ["Stichting voor Christelijke Filosofie", "NL", "500,00"],
      ],
      WMCES: [
        ["Ajatushautomo Kompassi ry", "FI", "500,00"],
        [
          "AT&T Global Networks Services Belgium Luxembourg SPRL",
          "BE",
          "16.640,00",
        ],
        ["GLOBSEC Policy Institute", "SK", "7.068,00"],
        ["Google Belgium NV", "BE", "18.000,00"],
        ["Evropská Akademie Pro Demokracii", "CZ", "1.294,01"],
        ["Evropské hodnoty z.s.", "CZ", "10.132,26"],
        ["Fundacja im. Kazimierza Pulaskiego", "PL", "1.500,00"],
        ["Microsoft NV/SA", "BE", "12.000,00"],
        ["Sky Deutschland Gmbh", "DE", "18.000,00"],
      ],
    },
  },
};
